name: Verify whether CI is ready for Rust Toolchain builds

on:
  workflow_dispatch

jobs:
  check-builders:
    name: Check builders
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "macos-m1-self-hosted", "macos-x86_64-self-hosted", "x86_64-pc-windows-gnu-self-hosted", "windows-x86_64-self-hosted" ]
    steps:
      - name: Simple test
        run: echo "Test"
